#! /bin/sh

docker run --read-only -it \
	-v /opt/github/auto-skew-elle/etc:/usr/local/etc \
	-v /usr/local/htdocs:/opt/htdocs \
	-v /usr/local/pems:/opt/pems \
	--env-file /usr/local/etc/autosql.env -p 800:443 auto-skew-elle
