#! /bin/sh
# (c) Copyright 2019-2020, James Stevens ... see LICENSE for details
# Alternative license arrangements possible, contact me for more information

if test "${SYSLOG_SERVER}"
	then
		exec /sbin/syslogd -n -R ${SYSLOG_SERVER}
	else
		exec /sbin/syslogd -n -O -
	fi
