#! /bin/sh
# (c) Copyright 2019-2020, James Stevens ... see LICENSE for details
# Alternative license arrangements are possible, contact me for more information

cd /usr/local/bin
exec gunicorn --bind unix:/ram/auto_sql_$1.sock wsgi
