#! /bin/sh
# (c) Copyright 2019-2020, James Stevens ... see LICENSE for details
# Alternative license arrangements possible, contact me for more information


for file in $(find /etc/start.d/ -type f)
do
	. ${file}
done


mkdir /run/nginx
chown nginx: /run/nginx


{
echo "::respawn:/usr/local/bin/start_syslogd"

sessions=5
if test "${AUTO_SQL_SESSIONS}"; then sessions="${AUTO_SQL_SESSIONS}"; fi
x=0
while test ${x} -lt ${sessions}
    do
        x=$(expr ${x} + 1)
        echo "::respawn:/usr/local/bin/start_wsgi ${x}"
    done

echo "::respawn:/usr/local/bin/start_nginx"

cat /etc/inittab.d/* 2>/dev/null

} > /ram/inittab

exec /sbin/init
